Trade validation logic
1smay3/Alpaca-PortfolioManager pull request #6
Opened 2021-12-20 20:56 UTC by 1smay3

2021-12-20 21:00 UTC, nathan-may commented on app/repository/alpaca/models/TradeValidator.py
> +def _is_buy_valid(instruction: Instruction) -> bool:
This will only ever return True, or will break early and throw `ValueError`. Definitely something to amend in future

2021-12-20 21:01 UTC, nathan-may commented on app/repository/alpaca/models/TradeValidator.py
> +        notional = ins.weight * portfolio_value
What is the point in this

2021-12-20 21:01 UTC, nathan-may commented on app/repository/alpaca/models/TradeValidator.py
> +_is_buy_valid(test_trade)
What's the point here

2021-12-20 21:02 UTC, nathan-may requested changes
Only merge this when it actually does something

2021-12-23 20:21 UTC, nathan-may commented on app/repository/alpaca/alpaca_service.py
> +from app.config.secrets import paper_key, paper_secret
Change yours locally @1smay3

2021-12-23 20:21 UTC, nathan-may commented on app/repository/alpaca/alpaca_service.py
> -class IAlpacaService(Protocol):
Removed interface as it doesn't add any value in python

2021-12-23 20:24 UTC, nathan-may commented on app/util/TradeValidator.py
> +pm = PortfolioManager()
@1smay3 `main` will create the one and only instance of each of these. It'll just pass what it has in memory to these top level functions. Otherwise we'll have lots of different instances of the same class floating around. In this case, `account_handler` won't have an account in it.

2021-12-23 20:42 UTC, nathan-may commented on app/util/TradeValidator.py
> +def _current_portfolio(positions: Positions, personal_account: LocalAccount):
Loads of commented out code in this class that either needs to be fixed or removed. This class should not have any dependencies, so each function should be a simple n:1 which returns either a primitive or a pre-defined model. If there are calls that need to be made ahead of time (namely, ensuring that the account is up to date) then they should be performed by the caller first, or we should implement some kind of system that delegates to this class after it refreshes the account. *And* it should ensure that the account update call succeeds before proceeding in this chain of logic which results in an actual trade being placed.

2021-12-23 20:43 UTC, nathan-may commented on app/util/TradeValidator.py
> +    :return: @1smay3
Be sure to doc each function here and provide info about the return type and what it actually is, to the layman

2021-12-23 20:53 UTC, nathan-may commented on app/util/TradeValidator.py
> +    """ CLEANING TO REMOVE AMD FROM MANUAL TRADE FOR NOW """
This is code which acts on some test data which is mixed in with production stuff. 

It should either be test code or production code. The function should work properly and we can feed in the fake portfolio in a unit test. Plz fix!

2021-12-23 22:57 UTC, closed without merging

2021-12-23 22:58 UTC, 1smay3 commented
No merge as WIP